<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_drop-zone__thumb</name>
   <tag></tag>
   <elementGuidId>62882d58-615e-40cd-96fa-49aeab6199aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.drop-zone__thumb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d062f04f-f1fd-4f85-96c4-e1ab413a39d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>drop-zone__thumb</value>
      <webElementGuid>c893323b-aea6-41f3-af3c-fa07ceca7f66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>thumbnail.png</value>
      <webElementGuid>cc9dbc2a-0e7d-418d-9bcd-e191386ea247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;drop-zone&quot;]/div[@class=&quot;drop-zone__thumb&quot;]</value>
      <webElementGuid>88d82ca1-19d8-41f0-bc1b-704a08feaed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Simple Drag and Drop File Upload Tutor_f60615/iframe__CodePen</value>
      <webElementGuid>9e68c831-0910-4943-a8ee-2db875f54dfe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div</value>
      <webElementGuid>bbb4b0c5-2da7-4013-a3c3-adf7719c2f03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
