<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Select images_upload</name>
   <tag></tag>
   <elementGuidId>6d382219-3e20-47e6-92ef-b77988694841</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#upload</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='upload']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#upload</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>64a35733-e4af-4090-8466-708ff6fa6d9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>d3b98ace-5f9e-4d9f-9ed5-8199f901cd6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>upload</value>
      <webElementGuid>7ba4ef11-7b0a-4bf6-882f-5afdc0c6a217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>upload</value>
      <webElementGuid>37d01826-33ff-47fc-a65c-0027851f4a2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>upload</value>
      <webElementGuid>460f0f7f-4ee3-4866-9699-02bfbe5731d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>image/*</value>
      <webElementGuid>58a65ddb-1a52-4b65-a17e-f95c88d91fd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;upload&quot;)</value>
      <webElementGuid>f6446e9a-3794-4741-92b7-2662ce957f26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='upload']</value>
      <webElementGuid>440913aa-ae77-4bce-bddd-fc9fa3d38403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainView']/div/div[5]/form/div/input</value>
      <webElementGuid>5d312cdd-33eb-4641-8b1b-bf807482d222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>24f581e4-a662-41e9-8e50-4b119fb7afbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'upload' and @name = 'upload']</value>
      <webElementGuid>ba09e534-c177-46fe-80c5-6bafcda03490</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
