<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Drag and drop files hereor_fileInput</name>
   <tag></tag>
   <elementGuidId>a7fc32f3-6faa-4f0c-baf2-6be7d313f280</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fileInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fileInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#fileInput</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e9131d1a-1594-49cc-80fe-9c6d9686bd20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>81d54471-62e8-4997-a635-a579e24a287a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fileInput</value>
      <webElementGuid>da027652-00f4-4c21-ad16-49ed583ff5f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fileInput&quot;)</value>
      <webElementGuid>22c9f1f4-cc09-4a77-93da-6de4479027b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fileInput']</value>
      <webElementGuid>f1d9730e-688a-427e-86ce-25e599cb3158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dropZone']/div/input</value>
      <webElementGuid>f89c0529-0438-47c9-8ed1-4b94efac3e0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>83d1035e-d709-4d0a-afb1-47281501773a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'fileInput']</value>
      <webElementGuid>27e928df-4dcf-4732-b81a-e2110868e4d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
