<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_thumbnail.png (16.33 KB)</name>
   <tag></tag>
   <elementGuidId>e3451f04-15ec-4a8a-b491-42ec05d25686</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='fileList']/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;thumbnail.png (16.33 KB)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>07ab5a53-0f2b-48e3-b7e8-5741f6a4cea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>thumbnail.png (16.33 KB)</value>
      <webElementGuid>25c17d58-d989-4983-94ad-c17865f20cdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fileList&quot;)/p[1]</value>
      <webElementGuid>6ee3517b-62d9-4e54-a515-49a199004d35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fileList']/p</value>
      <webElementGuid>2196aa79-22c6-47ac-88c3-a3cd3b0feb79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='thumbnail.png (16.33 KB)']/parent::*</value>
      <webElementGuid>d6e71494-51e0-4123-850d-31ee9e70703b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>549acc6d-3e01-4f09-b803-42c1f0c57d80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'thumbnail.png (16.33 KB)' or . = 'thumbnail.png (16.33 KB)')]</value>
      <webElementGuid>1e9c2264-d0d5-44c2-8287-2aea28ffa228</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
